namespace Tickets.Models.Enums
{
    public enum CatalogGroupEnum
    {
        GeneralStatus = 1,
        LogActions = 2,
        ProspectGroup = 3,
        ByFraction = 4,
        PrintTechnique = 5,
        TypeApproval = 6,
        ProspectStatu = 7,
        WorkflowProccessStatuEnum = 8,
        WorkflowStatu = 9,
        Gender = 10,
        MaritalStatus = 11,
        ClientGroup = 12,
        CheckIn = 13,
        ClientType = 14,
        SolteoCommodity = 15,
        DepartmentNames = 16,
        EmployeeOffice = 17,
        TypesAwardGroup = 18,
        TypesAwardCreation = 19,
        ProspectPrice = 20,
        TicketStatus = 21,
        RaffleAwardType = 22,
        InvoiceCondition = 23,
        RaffleStatus = 24,
        PaymentType = 25,
        CashStatu = 26,
        BachIdentifyStatu = 27,
        InvoiceStatu = 28,
        AllocationStatu = 29,
        ClientStatu = 30,
        TicketReprintStatu = 31,
        TicketsDesing = 33,
        RaffleXpiredTime = 35,
        XpriedInvoiceTime = 36,
        AllocationType = 37,
        AwardCertificationStatu = 38,
        NoteCreditType = 39,
        ElectronicSalesStatus = 40,
        TaxReceiptType = 41,
        TaxReceiptStatu = 42,
        TaxReceiptNumberStatu = 43,
        CashAdvances = 46,
        AccountReceivableType = 47,
        DocumentType = 48,
        OriginAccount = 56,
        AccountType = 57,
        PaymentPeriodicity = 58,
        BankAccountCatalog = 59
    }
}
