//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agency
    {
        public Agency()
        {
            this.OverduelBills = new HashSet<OverduelBill>();
            this.OverduelBills1 = new HashSet<OverduelBill>();
            this.Cashes = new HashSet<Cash>();
            this.Invoices = new HashSet<Invoice>();
            this.webpages_Roles = new HashSet<webpages_Roles>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public int GroupId { get; set; }
        public int Province { get; set; }
        public int Town { get; set; }
        public int Section { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public int Statu { get; set; }
        public System.DateTime IntDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
    
        public virtual ICollection<OverduelBill> OverduelBills { get; set; }
        public virtual ICollection<OverduelBill> OverduelBills1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Cash> Cashes { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
    }
}
