//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public Award()
        {
            this.Award1 = new HashSet<Award>();
            this.RaffleAwards = new HashSet<RaffleAward>();
        }
    
        public int Id { get; set; }
        public int ProspectId { get; set; }
        public int OrderAward { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> SourceAward { get; set; }
        public Nullable<int> Terminal { get; set; }
        public decimal Value { get; set; }
        public decimal TotalValue { get; set; }
        public int ByFraction { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public int TypesAwardId { get; set; }
    
        public virtual ICollection<Award> Award1 { get; set; }
        public virtual Award Award2 { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual Prospect Prospect { get; set; }
        public virtual TypesAward TypesAward { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<RaffleAward> RaffleAwards { get; set; }
    }
}
