//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashClose
    {
        public int Id { get; set; }
        public int CashId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public decimal ToktalCashCalculated { get; set; }
        public decimal TotalCheckCalculated { get; set; }
        public decimal TotalCardCalculated { get; set; }
        public decimal ToktalCashRegistered { get; set; }
        public decimal TotalCheckRegistered { get; set; }
        public decimal TotalCardRegistered { get; set; }
        public int UserStartId { get; set; }
        public int UserEndId { get; set; }
        public decimal TotalStart { get; set; }
        public int Statu { get; set; }
    
        public virtual Cash Cash { get; set; }
    }
}
