//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public Cash()
        {
            this.CashCloses = new HashSet<CashClose>();
            this.IdentifyBachPayments = new HashSet<IdentifyBachPayment>();
            this.ReceiptPayments = new HashSet<ReceiptPayment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AgencyId { get; set; }
        public decimal OpenValue { get; set; }
        public int Statu { get; set; }
        public System.DateTime CraeteDate { get; set; }
        public int CreateUser { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CashClose> CashCloses { get; set; }
        public virtual ICollection<IdentifyBachPayment> IdentifyBachPayments { get; set; }
        public virtual ICollection<ReceiptPayment> ReceiptPayments { get; set; }
    }
}
