//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public Catalog()
        {
            this.Awards = new HashSet<Award>();
            this.Clients = new HashSet<Client>();
            this.Logs = new HashSet<Log>();
            this.Prospect_Price = new HashSet<Prospect_Price>();
            this.Users = new HashSet<User>();
            this.WorkflowType_User = new HashSet<WorkflowType_User>();
            this.WorkflowProccesses = new HashSet<WorkflowProccess>();
            this.WorkflowTypes = new HashSet<WorkflowType>();
            this.TaxReceipts = new HashSet<TaxReceipt>();
            this.TaxReceiptNumbers = new HashSet<TaxReceiptNumber>();
            this.Winners = new HashSet<Winner>();
            this.Winners1 = new HashSet<Winner>();
            this.TicketAllocationNumber_Delete = new HashSet<TicketAllocationNumber_Delete>();
            this.TicketAllocationNumbers = new HashSet<TicketAllocationNumber>();
            this.OtherIncomes = new HashSet<OtherIncome>();
            this.OtherIncomes1 = new HashSet<OtherIncome>();
            this.OtherIncomes2 = new HashSet<OtherIncome>();
            this.OtherIncomes3 = new HashSet<OtherIncome>();
            this.OtherIncomeDetails = new HashSet<OtherIncomeDetail>();
        }
    
        public int Id { get; set; }
        public int IdGroup { get; set; }
        public string NameGroup { get; set; }
        public int IdDetail { get; set; }
        public string NameDetail { get; set; }
        public string Description { get; set; }
        public bool Statu { get; set; }
        public string Description2 { get; set; }
    
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<Prospect_Price> Prospect_Price { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<WorkflowType_User> WorkflowType_User { get; set; }
        public virtual ICollection<WorkflowProccess> WorkflowProccesses { get; set; }
        public virtual ICollection<WorkflowType> WorkflowTypes { get; set; }
        public virtual ICollection<TaxReceipt> TaxReceipts { get; set; }
        public virtual ICollection<TaxReceiptNumber> TaxReceiptNumbers { get; set; }
        public virtual ICollection<Winner> Winners { get; set; }
        public virtual ICollection<Winner> Winners1 { get; set; }
        public virtual ICollection<TicketAllocationNumber_Delete> TicketAllocationNumber_Delete { get; set; }
        public virtual ICollection<TicketAllocationNumber> TicketAllocationNumbers { get; set; }
        public virtual ICollection<OtherIncome> OtherIncomes { get; set; }
        public virtual ICollection<OtherIncome> OtherIncomes1 { get; set; }
        public virtual ICollection<OtherIncome> OtherIncomes2 { get; set; }
        public virtual ICollection<OtherIncome> OtherIncomes3 { get; set; }
        public virtual ICollection<OtherIncomeDetail> OtherIncomeDetails { get; set; }
    }
}
