//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationNumber
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public int RaffleAwardId { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Fractions { get; set; }
    
        public virtual User User { get; set; }
        public virtual RaffleAward RaffleAward { get; set; }
    }
}
