//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicTicketSale
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int RaffleId { get; set; }
        public int FractionFrom { get; set; }
        public int FractionTo { get; set; }
        public int TicketAllocationNimberId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int Statu { get; set; }
        public string PhoneNumber { get; set; }
        public string Cedula { get; set; }
        public string COD_AUTH { get; set; }
        public Nullable<int> PDV_ID { get; set; }
        public Nullable<int> TicketAllocationId { get; set; }
        public string PDV_NAME { get; set; }
        public string Province { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TicketAllocationNumber TicketAllocationNumber { get; set; }
        public virtual User User { get; set; }
        public virtual Raffle Raffle { get; set; }
    }
}
