//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicAwardPayed
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<int> FractionFrom { get; set; }
        public Nullable<int> NoTicket { get; set; }
        public Nullable<int> RaffleId { get; set; }
        public string AwardName { get; set; }
        public Nullable<decimal> Payed { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<System.DateTime> PayedDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> FractionTo { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Raffle Raffle { get; set; }
    }
}
