//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Agencies = new HashSet<Agency>();
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string DocumentNumber { get; set; }
        public int MaritalStatus { get; set; }
        public int Gender { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Province { get; set; }
        public int Town { get; set; }
        public int Section { get; set; }
        public string Addres { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int Statu { get; set; }
        public int AgencyId { get; set; }
        public int Department { get; set; }
        public int Office { get; set; }
        public int GroupId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
    
        public virtual ICollection<Agency> Agencies { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
