//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentifyBachPayment
    {
        public int Id { get; set; }
        public int CashId { get; set; }
        public int ClientId { get; set; }
        public decimal Value { get; set; }
        public string Note { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public int IdentifyBachId { get; set; }
        public int DiscountPercent { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> PayingFund { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string Nomenclature { get; set; }
        public Nullable<int> Digits { get; set; }
    
        public virtual Cash Cash { get; set; }
        public virtual Client Client { get; set; }
        public virtual IdentifyBach IdentifyBach { get; set; }
    }
}
