//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTicket
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public int TicketNumberAllocationId { get; set; }
        public int Quantity { get; set; }
        public decimal PricePerFraction { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual TicketAllocationNumber TicketAllocationNumber { get; set; }
    }
}
