//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public Invoice()
        {
            this.OverduelBills = new HashSet<OverduelBill>();
            this.OverduelBills1 = new HashSet<OverduelBill>();
            this.InvoiceTickets = new HashSet<InvoiceTicket>();
            this.ReceiptPayments = new HashSet<ReceiptPayment>();
            this.ReceivablePayments = new HashSet<ReceivablePayment>();
            this.TaxReceiptNumbersHistories = new HashSet<TaxReceiptNumbersHistory>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int AgencyId { get; set; }
        public int RaffleId { get; set; }
        public int Condition { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public decimal OutstandingBalance { get; set; }
        public int PaymentStatu { get; set; }
        public int Statu { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int PaymentType { get; set; }
        public Nullable<int> InvoiceExpredDay { get; set; }
        public decimal Discount { get; set; }
        public Nullable<int> DeleteUser { get; set; }
        public Nullable<int> TaxReceipt { get; set; }
        public Nullable<System.DateTime> TaxReceiptAssignmentDate { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<OverduelBill> OverduelBills { get; set; }
        public virtual ICollection<OverduelBill> OverduelBills1 { get; set; }
        public virtual Raffle Raffle { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<InvoiceTicket> InvoiceTickets { get; set; }
        public virtual ICollection<ReceiptPayment> ReceiptPayments { get; set; }
        public virtual ICollection<ReceivablePayment> ReceivablePayments { get; set; }
        public virtual ICollection<TaxReceiptNumbersHistory> TaxReceiptNumbersHistories { get; set; }
    }
}
