//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int Id { get; set; }
        public int Action { get; set; }
        public string Module { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Datos { get; set; }
    
        public virtual Catalog Catalog { get; set; }
    }
}
