//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteCredit
    {
        public NoteCredit()
        {
            this.NoteCreditReceiptPayments = new HashSet<NoteCreditReceiptPayment>();
            this.IdentifyBaches = new HashSet<IdentifyBach>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public decimal TotalCash { get; set; }
        public decimal TotalRest { get; set; }
        public System.DateTime NoteDate { get; set; }
        public int Statu { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Concepts { get; set; }
        public int DiscountPercent { get; set; }
        public Nullable<int> RaffleId { get; set; }
        public Nullable<int> TypeNote { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Raffle Raffle { get; set; }
        public virtual ICollection<NoteCreditReceiptPayment> NoteCreditReceiptPayments { get; set; }
        public virtual ICollection<IdentifyBach> IdentifyBaches { get; set; }
    }
}
