//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteCreditReceiptPayment
    {
        public int ReceiptPaymentId { get; set; }
        public int NoteCreditId { get; set; }
        public decimal TotalCash { get; set; }
    
        public virtual NoteCredit NoteCredit { get; set; }
        public virtual ReceiptPayment ReceiptPayment { get; set; }
    }
}
