//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherIncome
    {
        public OtherIncome()
        {
            this.OtherIncomeDetails = new HashSet<OtherIncomeDetail>();
        }
    
        public int Id { get; set; }
        public string NoCatalogAccount { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> Origin { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string Description { get; set; }
        public Nullable<int> Periodicity { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual Catalog Catalog1 { get; set; }
        public virtual Catalog Catalog2 { get; set; }
        public virtual Catalog Catalog3 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OtherIncomeDetail> OtherIncomeDetails { get; set; }
    }
}
