//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherIncomesGroup
    {
        public OtherIncomesGroup()
        {
            this.OtherIncomeDetails = new HashSet<OtherIncomeDetail>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> LengthZero { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string DocumentNumber { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual ICollection<OtherIncomeDetail> OtherIncomeDetails { get; set; }
        public virtual User User { get; set; }
    }
}
