//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherIncomeDetail
    {
        public int Id { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> OtherIncomeId { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
    
        public virtual OtherIncome OtherIncome { get; set; }
        public virtual User User { get; set; }
    }
}
