//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverduelBill
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int ClientId { get; set; }
        public string ClientName { get; set; }
        public string ClientTradeName { get; set; }
        public int RaffleId { get; set; }
        public string RaffleName { get; set; }
        public int AgencyId { get; set; }
        public System.DateTime OverduelBillAddedDate { get; set; }
        public Nullable<System.DateTime> OverduelBillDate { get; set; }
    
        public virtual Agency Agency { get; set; }
        public virtual Agency Agency1 { get; set; }
        public virtual Client Client { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Invoice Invoice1 { get; set; }
        public virtual Raffle Raffle { get; set; }
        public virtual Raffle Raffle1 { get; set; }
    }
}
