//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProspectFraction
    {
        public int ProspectId { get; set; }
        public int Fraction { get; set; }
    
        public virtual Prospect Prospect { get; set; }
    }
}
