//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospect
    {
        public Prospect()
        {
            this.Awards = new HashSet<Award>();
            this.Prospect_Price = new HashSet<Prospect_Price>();
            this.Raffles = new HashSet<Raffle>();
            this.ProspectFractions = new HashSet<ProspectFraction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int GroupId { get; set; }
        public int Production { get; set; }
        public int LeafNumber { get; set; }
        public int LeafFraction { get; set; }
        public int ImpresionType { get; set; }
        public int Statu { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public decimal Price { get; set; }
        public decimal MaxReturnTickets { get; set; }
        public System.DateTime ExpirateDate { get; set; }
    
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<Prospect_Price> Prospect_Price { get; set; }
        public virtual ICollection<Raffle> Raffles { get; set; }
        public virtual ICollection<ProspectFraction> ProspectFractions { get; set; }
    }
}
