//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospect_Price
    {
        public int Id { get; set; }
        public int ProspectId { get; set; }
        public int PriceId { get; set; }
        public decimal TicketPrice { get; set; }
        public decimal SeriePrice { get; set; }
        public decimal FactionPrice { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual Prospect Prospect { get; set; }
    }
}
