//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaffleAward
    {
        public RaffleAward()
        {
            this.AwardCertifications = new HashSet<AwardCertification>();
            this.CertificationNumbers = new HashSet<CertificationNumber>();
        }
    
        public int Id { get; set; }
        public int AwardId { get; set; }
        public int RaffleId { get; set; }
        public long ControlNumber { get; set; }
        public int Fraction { get; set; }
        public bool Paymentd { get; set; }
        public Nullable<int> PaymentRequestId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public int RaffleAwardType { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual ICollection<AwardCertification> AwardCertifications { get; set; }
        public virtual ICollection<CertificationNumber> CertificationNumbers { get; set; }
        public virtual Raffle Raffle { get; set; }
    }
}
