//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RRentabilidadSorteo
    {
        public int Id { get; set; }
        public int RaffleId { get; set; }
        public int CantBilletes { get; set; }
        public int CantSeries { get; set; }
        public int TotalHojas { get; set; }
        public int AsignFracciones { get; set; }
        public decimal AsignFraMonto { get; set; }
        public int AsignFraFacturas { get; set; }
        public decimal MontoFraFacturas { get; set; }
        public int AsignFraNoFacturadas { get; set; }
        public decimal MontoFraNoFacturadas { get; set; }
        public int FraDevueltasPorClientes { get; set; }
        public decimal MontoDevueltoPorClientes { get; set; }
        public int VentaFraccionesCliente { get; set; }
        public decimal MontoVentaFraCliente { get; set; }
        public decimal DevolucionPremiada { get; set; }
        public decimal MontoDevueltoPorClient { get; set; }
        public decimal GanadoresPublicos { get; set; }
        public decimal NoImpreso { get; set; }
        public decimal Pagado { get; set; }
        public decimal PendientePago { get; set; }
        public decimal Efectivo { get; set; }
        public decimal PagadoConPremios { get; set; }
        public decimal otros { get; set; }
    
        public virtual Raffle Raffle { get; set; }
    }
}
