//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public int Id { get; set; }
        public Nullable<int> MaxReturnTickets { get; set; }
        public string LoteryAdmin { get; set; }
        public int TicketDesign { get; set; }
        public int RaffleXpiredTime { get; set; }
        public Nullable<int> LawDiscountPercentMayor { get; set; }
        public string Cargo { get; set; }
    }
}
