//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public int Id { get; set; }
        public Nullable<int> MaxReturnTickets { get; set; }
        public string LoteryAdmin { get; set; }
        public int TicketDesign { get; set; }
        public int RaffleXpiredTime { get; set; }
        public Nullable<int> LawDiscountPercentMayor { get; set; }
        public string Cargo { get; set; }
        public string ControlPremio { get; set; }
        public string ControlPremioCargo { get; set; }
        public string CajaGeneral { get; set; }
        public string CajaGeneralCargo { get; set; }
        public string Inspectoria { get; set; }
        public string InspectoriaCargo { get; set; }
        public string CreditosCobrosCargo { get; set; }
        public string ProduccionSorteo { get; set; }
        public string ProduccionSorteoCargo { get; set; }
        public string Facturacion { get; set; }
        public string FacturacionCargo { get; set; }
        public string CreditosCobros { get; set; }
        public string Comercial { get; set; }
        public string ComercialCargo { get; set; }
        public Nullable<int> LawRetentPercent { get; set; }
    }
}
