//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketReturn
    {
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int RaffleId { get; set; }
        public int FractionFrom { get; set; }
        public int FractionTo { get; set; }
        public int TicketAllocationNimberId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime ReturnedDate { get; set; }
        public string ReturnedGroup { get; set; }
        public int Statu { get; set; }
        public decimal Discount { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Raffle Raffle { get; set; }
        public virtual TicketAllocationNumber TicketAllocationNumber { get; set; }
        public virtual User User { get; set; }
    }
}
