//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSuscriber
    {
        public TicketSuscriber()
        {
            this.TicketSuscriberNumbers = new HashSet<TicketSuscriberNumber>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public int FractionFrom { get; set; }
        public int FractionTo { get; set; }
        public int Statu { get; set; }
        public int Createuser { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TicketSuscriberNumber> TicketSuscriberNumbers { get; set; }
    }
}
