//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAllocationNumber
    {
        public TicketAllocationNumber()
        {
            this.IdentifyNumbers = new HashSet<IdentifyNumber>();
            this.InvoiceTickets = new HashSet<InvoiceTicket>();
            this.TicketRePrintNumbers = new HashSet<TicketRePrintNumber>();
            this.TicketReturns = new HashSet<TicketReturn>();
            this.ElectronicTicketSales = new HashSet<ElectronicTicketSale>();
        }
    
        public int Id { get; set; }
        public long Number { get; set; }
        public bool Invoiced { get; set; }
        public bool Printed { get; set; }
        public Nullable<System.DateTime> PrintedDate { get; set; }
        public string ControlNumber { get; set; }
        public int Statu { get; set; }
        public int CreateUser { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int TicketAllocationId { get; set; }
        public int FractionFrom { get; set; }
        public int FractionTo { get; set; }
        public Nullable<int> RaffleId { get; set; }
        public Nullable<bool> Consignated { get; set; }
        public Nullable<int> UserConsigned { get; set; }
        public Nullable<int> NoOrden { get; set; }
        public Nullable<int> No_Ticket_Electronico { get; set; }
        public Nullable<int> TicketType { get; set; }
    
        public virtual ICollection<IdentifyNumber> IdentifyNumbers { get; set; }
        public virtual ICollection<InvoiceTicket> InvoiceTickets { get; set; }
        public virtual TicketAllocation TicketAllocation { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TicketRePrintNumber> TicketRePrintNumbers { get; set; }
        public virtual ICollection<TicketReturn> TicketReturns { get; set; }
        public virtual ICollection<ElectronicTicketSale> ElectronicTicketSales { get; set; }
        public virtual Catalog Catalog { get; set; }
        public virtual Raffle Raffle { get; set; }
    }
}
