//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Town
    {
        public Town()
        {
            this.Clients = new HashSet<Client>();
            this.DistTowns = new HashSet<DistTown>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ProvinceId { get; set; }
    
        public virtual ICollection<Client> Clients { get; set; }
        public virtual ICollection<DistTown> DistTowns { get; set; }
        public virtual Province Province { get; set; }
    }
}
