//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public Workflow()
        {
            this.WorkflowProccesses = new HashSet<WorkflowProccess>();
        }
    
        public int Id { get; set; }
        public int ProcessId { get; set; }
        public int WorkflowTypeId { get; set; }
        public int Statu { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
    
        public virtual User User { get; set; }
        public virtual WorkflowType WorkflowType { get; set; }
        public virtual ICollection<WorkflowProccess> WorkflowProccesses { get; set; }
    }
}
