//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tickets.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowType
    {
        public WorkflowType()
        {
            this.Workflows = new HashSet<Workflow>();
            this.WorkflowType_User = new HashSet<WorkflowType_User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Statu { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUser { get; set; }
    
        public virtual Catalog Catalog { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Workflow> Workflows { get; set; }
        public virtual ICollection<WorkflowType_User> WorkflowType_User { get; set; }
    }
}
